Object not set to an instance of an object
ridercz/AutoACME pull request #35
Opened 2019-01-08 21:09 UTC by rokx

I was receiving "object not set to an instance of an object" exception when trying to create certificate for multiple subdomains. 
Updated packages and expanded the creation of AcmeAccount. I no longer receive the exception.

2019-01-09 00:13 UTC, avonwyss commented
These changes are problematic. Specifically the binding redirects of `System.Net.Http` must remain 0.0.0.0-4.2.0.0 => 4.1.1.3 (or whatever version is in the NuGet package). Google will give you plenty of hits like [this](https://stackoverflow.com/questions/47570912/strange-issue-with-system-net-http-4-2-0-0-not-found/47577209) when you search for the issues related to these versions.

Also I don't see how your changes might affect the exception you were getting, since the code in itself is semantically the same. I wonder if there was some other problem (network or whatever) when you tried before your changes. May I kindly ask you to try whether the version without your changes does work or not, and if not post the full exception details?

2019-01-09 00:16 UTC, avonwyss requested changes
Please change System.Net.Http binding redirects to 0.0.0.0-4.2.0.0 => 4.1.1.3, and test whether these changes actually fix anything.

2019-01-10 21:00 UTC, rokx commented
This is the verbose output i am getting with the latest version from your master.

> C:\\...\\AutoACMEtest>autoacme.exe addhost "domain.com example.domain.com" /verbose
> ...
> Reading configuration from 'C:\\...\\AutoACMEtest\autoacme.json'...OK
> Checking host...OK
> Requesting certificate for domain.com example.domain.com:
>   Using server https://acme-staging-v02.api.letsencrypt.org/directory
>   Creating registration for 'ro*******om' and accept TOS...OK
>   Request failed!
>   Object reference not set to an instance of an object.
> 
>   System.NullReferenceException: Object reference not set to an instance of an object.
>    at Altairis.AutoAcme.Core.AutoAcmeContext.<RegisterAndLoginAsync>d__21.MoveNext()
>   Failed!
>   Unable to get certificate for new host.

Moving 
`                            Agreement = await context.TermsOfService().ConfigureAwait(true),`
after object creation solves null reference exception.

I removed the updated packages stuff.

2019-01-10 23:51 UTC, avonwyss approved these changes

2019-01-10 23:52 UTC, avonwyss commented
Thanks @rokx for cleaning up the PR, I can approve that. I'll let @ridercz take care of merging (and making a new release sometime).

2019-01-30 10:14 UTC, merged